name: polyclonal-paper
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pandas=1.3.5
  - plotnine=0.8.0
  - python=3.9
  - scikit-misc
  - scipy
